defaults: &defaults
  options:
    identity_map_enabled: true

development:
  <<: *defaults
  sessions:
    default:
      hosts: 
        - localhost
      database: build_notifier_development

test:
  <<: *defaults
  sessions:
    default:
      hosts: 
        - localhost
      database: build_notifier_test

staging:
  <<: *defaults
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

production:
  <<: *defaults
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
